name: Build React App

on:
  push:
    branches: [ master, automated_build ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install Dependencies
        run: npm install
        
      - name: Create .env file
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_API_PASSWORD: ${{ secrets.VITE_API_PASSWORD }}
        run: |
          touch .env
          echo VITE_API_URL=${VITE_API_URL} >> .env
          echo VITE_API_PASSWORD=${VITE_API_PASSWORD} >> .env
      
      - name: Build
        env:
          CI: true
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist
